services:
  # PHP 8.4 Service
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: turtleboard_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - turtleboard_network
    depends_on:
      - db

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: turtleboard_nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - turtleboard_network
    depends_on:
      - app

  # MySQL 8.4 Service
  db:
    image: mysql:8.4
    container_name: turtleboard_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: turtleboard
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: turtleboard_user
      MYSQL_PASSWORD: turtleboard_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - turtleboard_network

# Networks
networks:
  turtleboard_network:
    driver: bridge

# Volumes
volumes:
  mysql_data:
    driver: local